set
search_path to public;

drop procedure if exists create_sequence(text, text);

create procedure
create_sequence(seq_name text, schema_name text default 'public')
language plpgsql as
$$
BEGIN
   IF
NOT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE c.relkind = 'S'
        AND c.relname = seq_name
        AND n.nspname = schema_name
   ) THEN
      EXECUTE format('CREATE SEQUENCE public.%I', seq_name);
END IF;
END;
$$;

call create_sequence('products_id_seq');
call create_sequence('users_id_seq');

create table if not exists products
(
    id    bigint generated by default as identity
        primary key,
    name  varchar(255),
    price double precision not null
);

create index if not exists idx_name
    on products (name);

create index if not exists idx_price
    on products (price);

create table if not exists users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255),
    username varchar(255)
);

create index if not exists idx_username
    on users (username);

create index if not exists idx_email
    on users (email);

